import type { ChatUiLabelOverrides } from "@turingfocus/chat-ui-antd";

export const playgroundChatLabels: ChatUiLabelOverrides = Object.freeze({
  askUserCancel: "取消",
  askUserChatAboutThis: "聊聊这个问题",
  askUserLabel: "需要用户输入",
  askUserRequired: "此项为必填项。",
  askUserSubmit: "提交回答",
  askUserSubmitting: "正在提交",
  askUserUnavailable: "当前会话无法提交交互回答。",
  capabilityUnavailableDescription: "当前会话不支持此聊天能力。",
  capabilityUnavailableTitle: "能力不可用",
  composerLabel: "消息",
  composerPlaceholder: "输入消息",
  conversationListLabel: "会话列表",
  disconnectedDescription: "实时连接已断开，请检查连接后重试。",
  disconnectedTitle: "连接已断开",
  emptyDescription: "请选择一个会话开始聊天。",
  emptyTitle: "尚未选择会话",
  emptyTimeline: "暂无消息",
  errorDescription: "聊天内容暂时无法显示。",
  errorTitle: "出现错误",
  interrupt: "停止",
  interruptUnavailable: "当前无法停止",
  interrupting: "正在停止",
  jumpToLatest: "回到最新消息",
  loadingDescription: "正在准备会话。",
  loadingTitle: "正在加载会话",
  newMessages: "条新消息",
  noConversations: "暂无会话",
  retry: "重试",
  runStatusLabel: "运行状态",
  send: "发送",
  sending: "发送中",
  textSendingUnavailable: "当前无法发送文本消息。",
  timelineLabel: "会话时间线",
});
