import type {
  ChatResourceLabels,
  ChatUiLabelOverrides,
  ChatUiLabels,
} from "./types.js";

export const defaultChatResourceLabels: ChatResourceLabels = Object.freeze({
  screenshot: "Browser screenshot",
  generatedFile: "Generated file",
  fileTitle: "File",
  image: "Image",
  audio: "Audio",
  video: "Video",
  loading: "Loading resource…",
  retry: "Retry resource",
  open: "Open",
  download: "Download",
  opening: "Opening…",
  downloading: "Downloading…",
  unauthorized: "Sign in or check your access to this resource.",
  network: "Resource could not be reached. Check your connection and retry.",
  "not-found": "Resource was not found.",
  expired: "Resource link has expired. Retry to refresh it.",
  unsupported: "This resource format is not supported.",
  cancelled: "Resource loading cancelled.",
  unknown: "Resource action failed. Try again.",
});

export const defaultChatUiLabels: ChatUiLabels = Object.freeze({
  cacheSyncing: "Showing cached conversation. Syncing latest updates…",
  cacheStale: "Showing older cached content. Syncing latest updates…",
  cacheSyncFailed: "Could not sync. Cached content may be out of date.",
  cacheAttachmentUnavailable:
    "Some draft attachments need to be attached again.",
  cacheStorageFailed:
    "Local cache could not be saved or restored. Server loading is still available.",
  resource: defaultChatResourceLabels,
  attach: "Attach",
  askUserCancel: "Cancel",
  askUserChatAboutThis: "Chat about this",
  askUserLabel: "User input requested",
  askUserRequired: "This answer is required.",
  askUserSubmit: "Submit answers",
  askUserSubmitting: "Submitting",
  askUserUnavailable:
    "Interaction answers are unavailable in the current session.",
  capabilityUnavailableDescription:
    "This chat capability is not available in the current session.",
  capabilityUnavailableTitle: "Capability unavailable",
  composerLabel: "Message",
  composerPlaceholder: "Write a message",
  conversationListLabel: "Conversations",
  createConversation: "New conversation",
  createConversationConfirm: "Create",
  createConversationTitleLabel: "Conversation title",
  createConversationTitlePlaceholder: "Enter a conversation title",
  deleteConversation: "Delete conversation",
  deleteConversationCancel: "Cancel",
  deleteConversationConfirm: "Delete",
  deleteConversationPrompt: "Delete this conversation permanently?",
  disconnectedDescription:
    "Live updates are unavailable. Check the connection and try again.",
  disconnectedTitle: "Disconnected",
  emptyDescription: "Select a conversation to start chatting.",
  emptyTitle: "No conversation selected",
  errorDescription: "The chat could not be displayed.",
  errorTitle: "Something went wrong",
  emptyTimeline: "No messages yet",
  eventDetailClose: "Close event details",
  eventDetailEmpty: "Select an event to view its details.",
  eventDetailModeAuto: "Auto",
  eventDetailModeLabel: "Event detail mode",
  eventDetailModeModal: "Modal",
  eventDetailModeSplit: "Split",
  eventDetailSplitHandleLabel: "Resize event detail panes",
  eventDetailTitle: "Event details",
  interrupt: "Stop",
  interruptUnavailable: "Stop unavailable",
  interrupting: "Stopping",
  jumpToLatest: "Jump to latest",
  loadMoreConversations: "Load more conversations",
  renameConversation: "Rename conversation",
  renameConversationConfirm: "Rename",
  loadingDescription: "The conversation is being prepared.",
  loadingTitle: "Loading conversation",
  newMessages: "new messages",
  noConversations: "No conversations",
  openEventDetail: "Open event details",
  pastedTextTitle: "Pasted text",
  removeAttachment: "Remove attachment",
  removeLongText: "Remove pasted text",
  retry: "Try again",
  retryUpload: "Retry upload",
  runStatusLabel: "Run",
  send: "Send",
  sending: "Sending",
  textSendingUnavailable: "Text sending is unavailable.",
  timelineLabel: "Conversation timeline",
  newConversation: "New conversation",
  historyConversations: "History",
  noHistoryConversations: "No conversations",
  loadingHistoryConversations: "Loading conversations…",
  lifecycleStatus: Object.freeze({
    connecting: "Connecting…",
    joining: "Joining conversation…",
    active: "Connected",
    degraded:
      "Connected with best-effort recovery; transient updates may be missing.",
    reconnecting: "Connection lost. Reconnecting…",
    recovering: "Reconnected. Recovering missed updates…",
    "auth-required": "Sign in again to continue.",
    offline: "Chat is offline.",
    "subscription-failed": "Live updates could not be started.",
  }),
});

export const resolveChatUiLabels = (
  overrides: ChatUiLabelOverrides | undefined,
): ChatUiLabels => ({
  ...defaultChatUiLabels,
  ...overrides,
  resource: { ...defaultChatUiLabels.resource, ...overrides?.resource },
  lifecycleStatus: {
    ...defaultChatUiLabels.lifecycleStatus,
    ...overrides?.lifecycleStatus,
  },
});
